### ISSUE TITLE
CRAN page to GitHub repos links

### ISSUE THREAD

**Issue by HenrikBengtsson** [mpierrejean/acnr#10]
Add the following to DESCRIPTION so that the CRAN page links back to this GitHub repos:
```
URL: https://github.com/mpierrejean/acnr
BugReports: https://github.com/mpierrejean/acnr/issues
```
This makes it easy for constributors and people who give feedback to do so.

Likewise, edit the GitHub repos description (online) by adding link to the CRAN page.   This makes it easy to see that the package is on CRAN.

**Comment by pneuvial** [comment]
Done for the DESCRIPTION file.

I can't edit the GitHub repos description, I guess only the repos owner (@mpierrejean) can do it.

@mpierrejean, can you add something like: 

R package acnr: Annotated Copy-Number Regions https://cran.r-project.org/package=acnr

?

**Comment by mpierrejean** [comment]
Done
