### ISSUE TITLE
Add non-Tumorboosted data to the data files of the package

### ISSUE THREAD

**Issue by pneuvial** [mpierrejean/acnr#2]

**Comment by pneuvial** [comment]
Done for 'GSE29172' by adding two columns:

* `bT` : allelic ratios in the tumor before TumorBoost
* `bN` : allelic ratios in the normal

**Remains to be done for the other data sets**

**Comment by pneuvial** [comment]
1daa544d3c04b38f05d2e369be39cfcd6be528e0

**Comment by pneuvial** [comment]
Morgane, can you look into this for the other two data sets?

**Comment by mpierrejean** [comment]
Done for data set GSE13372 b3a38ba19c673831cdb5f8fe20b01889dbd96955

The other one is an Illumina data set and data on GEO is already normalized.

**Comment by pneuvial** [comment]
Just to clarify for "the other one" ie `GSE11976`: 

* It is an Illumina data set so TumorBoost is not really needed anyways.
* The allelic ratios in the normal *are* provided in the "0%" dilution, so we could add them. However I don't think it's useful for now.
* The data on GEO (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE11976) is not normalized (at least not fully, the signals are "X.raw", "Y.raw" etc.

but the data in the package is generated (see `acnr/inst/preprocessing/GSE11976/00.PrepareData.R`) from the normalized signals available from http://cbbp.thep.lu.se/~markus/software/BAFsegmentation/
