### ISSUE TITLE
Too long filenames

### ISSUE THREAD

**Issue by pneuvial** [mpierrejean/acnr#3]
> * checking for portable file names ... NOTE
> Found the following non-portable file paths:
>   acnr/inst/extdata/GSE13372/GenomeWideSNP_6/GSE13372,ASCRMAv2,HCC1143_GLEYSvsHCC1143BL_GLEYS,0,cnRegions.rds
>   acnr/inst/extdata/GSE13372/GenomeWideSNP_6/GSE13372,ASCRMAv2,HCC1143_GLEYSvsHCC1143BL_GLEYS,100,cnRegions.rds
> 
> Tarballs are only required to store paths of up to 100 bytes and cannot
> store those of more than 256 bytes, with restrictions including to 100
> bytes for the final component.
> See section ‘Package structure’ in the ‘Writing R Extensions’ manual.
> 

easy fix: remove the name of the data set in the file names, e.g.:

> acnr/inst/extdata/GSE13372/GenomeWideSNP_6/HCC1143_GLEYSvsHCC1143BL_GLEYS,0,cnRegions.rds
>   acnr/inst/extdata/GSE13372/GenomeWideSNP_6/HCC1143_GLEYSvsHCC1143BL_GLEYS,100,cnRegions.rds
>

**Comment by pneuvial** [comment]
If possible, better do

> acnr/inst/extdata/GSE13372/GenomeWideSNP_6/HCC1143,GLEYSvsBL_GLEYS,0,cnRegions.rds
> acnr/inst/extdata/GSE13372/GenomeWideSNP_6/HCC1143,GLEYSvsBL_GLEYS,100,cnRegions.rds

**Comment by mpierrejean** [comment]
Done
